# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-26 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FACT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='proveedor',
            new_name='descripcion',
        ),
    ]
