# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FACT', '0003_auto_20170425_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
