# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FACT', '0004_orden_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='proveedor',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
